export const SUPERLATIVES = [
  "The Shah Rukh Khan of the Batch 🌟",
  "Most Likely to Debug at 3AM 💻",
  "The One Who Actually Read the Docs 📖",
  "Best Supporting Actor in Group Projects 🎭",
  "The Human Stack Overflow 🔍",
  "Most Likely to Start a Startup Tomorrow 🚀",
  "The One Who Carried Every Group Project 💪",
  "Master of Last Minute Submissions ⏰",
  "The WiFi Whisperer 📶",
  "Most Likely to Become a CEO 👔",
  "The Chai Break Organiser ☕",
  "Best Dressed in Every Practical 👗",
  "The One Who Knew the Exam Syllabus 📚",
  "Most Likely to Sleep in Every Lecture 😴",
  "The Campus Legend 🏆",
  "The Google Search Champion 🔎",
  "Most Likely to Fix Your Computer 🖥️",
  "The Placement Season Hero 💼",
  "The One Who Never Missed Attendance 📋",
  "Most Likely to Go Abroad ✈️",
]